# Generated by Django 2.2.5 on 2019-09-18 03:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='queried_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
