# Generated by Django 2.2.5 on 2019-09-18 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleApp', '0002_product_queried_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='selling_number',
            field=models.CharField(default=0, max_length=40),
        ),
        migrations.AddField(
            model_name='product',
            name='shipment',
            field=models.CharField(default=0, max_length=40),
        ),
    ]
